---

- name: Create elk.repo from elk.repo.j2
  template:
    src: templates/elk.repo.j2
    dest: /etc/yum.repos.d/elk.repo

- name: Install Filebeat
  yum: 
    name: filebeat
    state: installed

#Copy the cert logstash certificate to the client server


- name: Create filebeat.yml from filebeat.yml.j2
  template:
    src: templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

