---
# Install elasticsearch 

- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Copy elk.repo from files to /etc/yum.repos.d/
  copy:
    src: elk.repo.j2
    dest: /etc/yum.repos.d/elk.repo

- name: Install Elasticsearch.
  yum: 
    name: elasticsearch
    state: installed

- name: Start Elasticsearch.
  service: 
    name: elasticsearch 
    state: started
    enabled: yes
  ignore_errors: true

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: 
    host: "{{ elasticsearch_network_host }}" 
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 200
