---
# Make system ready before installation of the ELK stack

- name: Install Java and wget
  yum:
    name:
      - java
      - wget
    state: present

- name: Disable selinux 
  selinux:
    state: disabled   

- name: Disable firewalld 
  systemd:
    name: firewalld
    state: stopped
